language: php

php:
  - '7.3'

install: composer update

script:
  - vendor/bin/infection --min-covered-msi=90 --min-msi=90

env:
  global:
    secure: GWspFT/kiBJ1N1/dVTlCX/TnibRi4n45IGwNR7wrMLiYFiocTkFV23rE4xt0rOCm3l7hbH25mOJQmaRDrfgpmF4XWnkKv7KlFAZqnwqMXHj0PpQr1bjA/wh8gK6X/Z3hcPQcVwP/IqsEcOSYnWGepWOClbGVX2Y34hb6NS4udMsAWQCg/DcCYMu820uKpFY2Mhhw5OtRPqCZLfEM87XaeNOMm8fMj2qoMFSK1g0L4l9tzI5zVfgf63YSJDinSc1MS5kmP0eZ1D2Xoq6D0rFQHteeilk86VNI7jgvxpvQrKNfMNmTVN4frlk0eNYQtnnCNehPbsSJvcW7QMxCaZknZtsGAm3/sPvN8JncgeZgq/5DB9oSbXfwp6vlq0Bluv0m+090UiMNW/CmqqulY131H3nAauUM6G6cP2EfpC1jpyjfCu34Fs/m4Skcut7bYFz/Irmum2RloHG5XrBYfuUd2REsEWsOT+vNpTJiSIT7YmtpGR7LlVEgk5uLQ5glp506nlaRCFydeeUaiHYbuAgirB0nUhtSJ9yXl55K5wDlQfr+LNujV76bzI4UvtO9NsuoyecHIk/jVhGXr3fmmb6Sr182njXdwbNmA6MRaP0cEG8HiH2lQElOC0JMUHeERLkURhUkSZHacp9cT9GEWPf/QWkWOi1oiGFey3rPRPSUt94=
