language: php

php:
  - '7.3'

install: composer update

script:
  - vendor/bin/infection --min-covered-msi=90 --min-msi=90

env:
  global:
    secure: A/s0gc5j0seXGPmHMHqKIjMkr6pzNm9LZ17y0bZpHYhb2b0AoyC1o+Z6iiu2PfsQn9TQrpJ6jZGkrdAkVMqUs9v0SWZyfktJUwgvN7y6OHqWFnGrohQ0zVowEhibQXh0q6GZF2jq0kqyG5G/sftviBIWJYAz9pHPoj9v9vntNLHIwR7R2PTh3ojdPpos4N6ucOtjAIbUrypCP9U61Pn0x/Uy3CoFKyFMRgRJu8yVtVCtAImp3xuvOi91Fl4upk4IDytO7MEbPjsbst35bNOLqV/IrEyp0WEXAaL/CKXAKF0T9Jm0NyQjqvgPb9Ri5dfqt2e7eZAc6ggRUqxU+ogMrskM/MEhCaaKF0gpzO0OFmmu/gRxBKXvphyz1Ldh9tvhPoS3X4CKWWtvM90wyeLWrBW4sa/Lp0FHeNmjmnOUNeXcMuqWn64+pnNFPc3heponhemYX03j9lrSGm+2/GhJ0OGMqh6Z4HmI0QbaQQaZFpQ9j6IPkGisLZrMwyENyFT4+s5b3w6bz+1eWXjfs6sQReb4DP4KbxozrE9SI3T2hEDlZ8gUdmt61uqTMXo8bJTjFTA3WnNydZoQSbn6Ek0Wtbu1JXi4oS860DLq3uK6+ILPtVpHF3HHWNjQkFu5/fs6lFuWV2P3+cHVrZIIkAYBNOB3oBoNLfmR0JEWDRR1bS8=
