language: php

php:
  - '7.3'

install: composer update

script:
  - vendor/bin/infection --min-covered-msi=90 --min-msi=90

env:
  global:
    - secure: lfIL0eFyF84Syj0Gc+gmSq8Lsht5sGtnEooM18xUfXfs0bsMhjfCpRMdC4UEemkzz7P5guJ+RCc0e7pRjFYz0PZGPGV5I2Ilzk1FafFw/MrkADCY0ZlzYuyqh0tG121fRt9hbwrliKk1hlBBBwnjN03jTqSTcvIKKTiY9zbpK6a/47C4UhQIw/2y3Gi69/Zyt446pC0zWDoh7rp8+NstIhwz7J6DXfW7lmFcVqAWbJgFExEmj8z8OBzmrnvgU8FhgXznomPHhGdEV+6B3uvqXDg+WSC5ASlEUevPYqUkysDL/36GyK+1V8vRTib+0tCKHBbAWa0A5/MTWSmVd7ExI0KZcOtB3tBvEDa0bOVXPkzJQfaIG6n9NXTwbXKJAmYwYwDFlIZ+HhW8NZ+m3/UN9bu30psLn0X5ARiGDV7c/9zDi84iP5bKH52FNKGX7ojIQKtI2fh8r47vDcmDmuRxoig4UOJXTA//JTjoQFdsf8fdJHcZI/3F07wQ5BxqhfOcxkkJ8c8LI4EXIreaenTFalYbpAH/sYMoIY+RzPfV+eR66IdeNS+JvyTLxxoBMjHAtHb/hvaFqjKmpn8/u+C3UDJvRGbjHkJQ7kygmLo+/diaJZ47K5jsb5h7UNtCekPI96SdJyOywZxhZMqb/vpMINtGAqmBNx75KfK5waY1Je0=
