language: php

php:
  - '7.3'

install: composer update

script:
  - vendor/bin/infection --min-covered-msi=90 --min-msi=90

env:
  global:
    - secure: 'iQralNsPK4yie8ZtuOe+o1xkzOgipn00knR4C2vtZZ3WaWszmipYd9GHNuhJBWf/EAKkJta3woAMoKkjpkDFBiySLEUo3AG4QHbT4uSVjjBL+WFT3ZbMdqUUbIj2iWqSisjcmtYNcVW/dRTWDVD2nPZ9BCccek9fhepZhke/+edZ540U1qJbQ0BQMmssKEXqairyYgDCP+AcGL66p5wlGyXWDdubvYrwdQbBueGikd9lw7J61/ynLeItqcLg3hY2pL0JDu557VS9P2PcxOy8K+jwzocdttWkOBrqEhlj5nXbukzjtQB7v1O2Aao+0t3wX+GXsQ90zhXJ+FLuo8Z2f7R+3Vp8AZeL6OpbMwTPoca68mDmzRPFQYOAbi1vBCEFWHT55enxIqpKJcY1BkWqVRKoF2TDQiJMO5aLezXIi2MHCAxqEMHwwPfbw0SJV4wYSH/aargd+G4A+WKAy71GKeYDvQ1Lz0ULH2BKdWvBuPGv/8WYuVnfzW5Tia6N0UsUKWE3U2/DnNUlXjjnuYfz0PFMvNaqs8h04Z6xWDNWJVE/d/mrhaTtpQBFT4imEdUDTZLPj/5X/SUcVEsD9invb2xNnrXQmddnCTNhHE47+/+j9CR0T5jwbp2SDjCTZ8k+3jwyEtQQCdE550eu1mxtdL9epy6jZnv4W3KWP33HOl0='
