language: php

php:
  - '7.3'

install: composer update

script:
  - vendor/bin/infection --min-covered-msi=90 --min-msi=90

env:
  global:
    secure: "CPPEy4rpqELs/fJnnRbRDfpCHImeYVby4QaK3k83z/B+8AEoSHVXIEy49iH86NL8xOagn5vntEoTyqkbYsXqLTIiKuaLpgwLHS+PL1zSZlZ3fDWsybzBVqGiDgSIwjgq7HTH41/nZV2xpsmA7ixVxnKFymj1/V8P8x4NkT3RzD4gsdNQRrQXGsWEl+Oi1Ea73Tnn/q0KX2tjjiMRmUW8koCt5tr86UlcFGkJKCd1ZqYiDdzbSJxctWHqvZ1HxBIzGh7nukbRT70ARZNkJ9HHBNQdyfBFxbp/ag/pOe/Rmoh0XVu0ilolqnva5j/2h6f1SgOSbIvAdabIvTCxgm4N+f620ywakGt4+OH1HCsQTeO2MClAlMAurHcHRgstNXzqRDT6R5xUJfoCrHSNwKFnuIOc0DK0gQAMDZQ3/jN/hotP4Qzs9x9CsfgdvWsoGjoPB2kYQwKNieThIFw/H0ul4o5+AMtkYpM1hrYP1dkrntYtXtq56dF0ce9n2AM8aa7yIT/9s9L272Ka4L/ZMdu+2QLCzne95T7mEslrwoI24Qgx3dNz0J4ZStB5vBDoBt6kGZdhfRNeH4V6C+z0G7mOUfm8G1hw3gd+ZEf3vuaHjSw+obhmSkqH1nryC3GdG449Ldkvb/qQVHLRNWJ1ir2GoJdetL6dg1caIIykzaFo3nk="
